### ISSUE TITLE
会有宏块大小不是16告警，然后cv2就会出问题。

### ISSUE THREAD

**Issue by yinjiaoyuan** [halfzm/faster-propainter#3]
RAFT: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:11<00:00,  9.14it/s]
feature propagation: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:29<00:00,  4.17it/s]
07/26/2024 09:39:00 - WARNING: IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (212, 160) to (224, 160) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0x65a4880] Warning: data is not aligned! This can lead to a speed loss
07/26/2024 09:39:02 - WARNING: IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (212, 160) to (224, 160) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0x55c9040] Warning: data is not aligned! This can lead to a speed loss
out_fp=./output/output.mp4
frame_width=576, frame_height=1024
frame_a type=<class 'numpy.ndarray'> mask_bg type=<class 'numpy.ndarray'>, frame_b type=<class 'numpy.ndarray'>, mask_fg type=<class 'numpy.ndarray'>, mask_fg shape=(160, 212)
frame_width=576, frame_height=1024
Traceback (most recent call last):
  File "start.py", line 86, in <module>
    start()
  File "start.py", line 72, in start
    merge_videos_with_mask(
  File "/opt/faster-propainter/pre_post_process.py", line 126, in merge_videos_with_mask
    frame_fg_masked = cv2.bitwise_and(
cv2.error: OpenCV(4.8.1) /io/opencv/modules/core/src/arithm.cpp:230: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'

**Comment by 01-111162-173** [comment]
这个怎么解决的呢
